### ISSUE TITLE
Error 500 bei Suche

### ISSUE THREAD

**Issue by tordans** [k-nut/osm-gtfs-checker#26]
https://osm-checker.k-nut.eu/search/karl-marx-straße erzeugt einen Fehler 500

>Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by k-nut** [comment]
This was fixed in e888f0aaac9c16e97b1c3964534c327d30c5534a and aa7ccd55f10f4db6df678dd15b75f2daf90d6255

Please note that search is case sensitive.

And oh my, this code is a mess :D
